stages:
  - deploy
  
deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$VM_IPADDRESS -p 22337 "cd /var/www/uzbcontent/uzbcontent-back && git pull && docker-compose up web -d --build"
    - ssh $SSH_USER@$VM_IPADDRESS -p 22337 "cd /var/www/uzbcontent/uzbcontent-back && docker-compose run --rm web python manage.py migrate"
  environment:
    name: production
    url: https://cp.uzbcontent.uz/
  only:
    - master
