# Generated by Django 5.0.2 on 2024-02-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
