# Generated by Django 5.0.2 on 2024-02-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_languages_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstranslation',
            name='thumbnail',
        ),
    ]
