# Generated by Django 5.0.2 on 2024-02-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='product',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='content.products'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_1080',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/1080p', verbose_name='video_1080'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_480',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/480p', verbose_name='video_480'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_720',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/720p', verbose_name='video_720'),
        ),
    ]
