# Generated by Django 5.0.2 on 2024-02-22 15:30

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_productstranslation_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstranslation',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default='thumbnails/Screenshot_from_2024-02-21_16-33-09.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
