# Generated by Django 5.0.2 on 2024-02-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_video_product_alter_video_video_1080_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='product',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='content.products'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('product', 'language')},
        ),
    ]
