# Generated by Django 5.0.2 on 2024-02-22 15:41

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_productstranslation_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstranslation',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=0.5, size=[1920, 1080], upload_to='thumbnails/'),
        ),
    ]
