# Generated by Django 5.0.2 on 2024-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_video_product_alter_video_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productstranslation',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/Screenshot_from_2024-02-18_12-41-01.png', upload_to='thumbnails/', verbose_name='thumbnail'),
            preserve_default=False,
        ),
    ]
