# Generated by Django 5.0.2 on 2024-02-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_video_thumbnail_productstranslation_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstranslation',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is_featured'),
        ),
    ]
