# Generated by Django 5.0.2 on 2024-02-23 10:57

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_productstranslation_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstranslation',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[640, 360], upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
    ]
