# Generated by Django 5.0.2 on 2024-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_productstranslation_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productstranslation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-19 08:30:39.126056 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
