# Generated by Django 5.0.2 on 2024-02-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_productstranslation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productstranslation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slugpagetranslation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_active',
        ),
        migrations.AddField(
            model_name='slugpage',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
