# Generated by Django 5.0.2 on 2024-03-01 15:11

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_audio_options_remove_audio_video_1080_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstranslation',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[640, 360], upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
    ]
