# Generated by Django 5.0.2 on 2024-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_languages_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='label',
            field=models.CharField(default='default', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LanguagesTranslation',
        ),
    ]
