# Generated by Django 5.0.2 on 2024-03-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_productstranslation_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstranslation',
            name='production',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='production'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='product',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='content.products'),
        ),
    ]
