# Generated by Django 5.0.2 on 2024-03-02 12:59

import apps.shared.django.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_productstranslation_production_alter_audio_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=apps.shared.django.utils.utils.audio_upload_path, verbose_name='audio'),
        ),
    ]
