# Generated by Django 5.0.2 on 2024-03-02 13:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_audio_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slugpage',
            name='slug',
            field=models.SlugField(max_length=510, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='slugpagetranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slugpagetranslation',
            name='title',
            field=models.CharField(max_length=510, unique=True, verbose_name='title'),
        ),
    ]
