# Generated by Django 5.0.2 on 2024-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_slugpage_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slugpagetranslation',
            name='title',
            field=models.CharField(max_length=510, verbose_name='title'),
        ),
    ]
