# Generated by Django 5.0.2 on 2024-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_slugpagetranslation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstranslation',
            name='producer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='producer'),
        ),
    ]
