# Generated by Django 5.0.2 on 2024-03-04 09:26

import apps.shared.django.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_productstranslation_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(default='audios/en/ALI_AND_ALIA.mp3', upload_to=apps.shared.django.utils.utils.audio_upload_path, verbose_name='audio'),
            preserve_default=False,
        ),
    ]
